---
apiVersion: v1
kind: Secret
metadata:
  name: hedgedoc.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/hedgedoc.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: hedgedoc-s3
spec:
  path: fsn-k3s/hedgedoc/s3
  keys:
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: hedgedoc-session
spec:
  path: fsn-k3s/hedgedoc/session
  keys:
    - secret
  type: Opaque
