---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: grafana-admin
spec:
  path: fsn-k3s/monitoring/grafana-admin-creds
  keys:
    - user
    - password
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: thanos-objectstorage
spec:
  path: fsn-k3s/monitoring/thanos-objectstorage
  type: Opaque
