---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: grafana-admin-creds
spec:
  path: fsn-k3s/monitoring/grafana-admin-creds
  keys:
    - username
    - password
  type: Opaque
