{
 "title": "GitLab CI jobs",
 "description": "This dashboard leverages the Prometheus exporter I wrote to fetch information about GitLab CI pipelines statuses. More information here: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "OWNER",
    "label": "owner",
    "query": "label_values(gitlab_ci_pipeline_id, project)"
   },
   {
    "name": "REF",
    "label": "ref",
    "query": "label_values(gitlab_ci_pipeline_id{project=~\"$OWNER.*\"}, ref)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;\"><img src=\"https://www.cloudfoundry.org/wp-content/uploads/2017/10/icon_gitlab_cf@2x.png\" width=80px/></p>"
   }
  },
  {
   "title": "JOBS #",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_job_run_count{project=~\"$OWNER.*\", ref=~\"$REF\"})"
    }
   ]
  },
  {
   "title": "FAILED JOBS #",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_job_status{status=\"failed\", project=~\"$OWNER.*\", ref=~\"$REF\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "RUNS # (in the last hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_ci_pipeline_job_run_count{project=~\"$OWNER.*\", ref=~\"$REF\"}[1h]))"
    }
   ]
  },
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "(gitlab_ci_pipeline_job_status{status=\"success\", project=~\"$OWNER.*\", ref=~\"$REF\"} * 1 > 0) or (gitlab_ci_pipeline_job_status{status=\"running\", project=~\"$OWNER.*\", ref=~\"$REF\"} * 2 > 0) or (gitlab_ci_pipeline_job_status{status!~\"success|running\", project=~\"$OWNER.*\", ref=~\"$REF\"} * 3 > 0)",
     "legendFormat": "{{project}}:{{ref}}:{{job_name}}"
    }
   ]
  },
  {
   "title": "Average Job Run Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - gitlab_ci_pipeline_job_timestamp{project=~\"$OWNER.*\", ref=~\"$REF\"})"
    }
   ]
  },
  {
   "title": "Average Job Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gitlab_ci_pipeline_job_duration_seconds{project=~\"$OWNER.*\", ref=~\"$REF\"})"
    }
   ]
  },
  {
   "title": "PIPELINE RUNS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gitlab_ci_pipeline_job_run_count[1m]) / increase(gitlab_ci_pipeline_job_run_count[1m])",
     "legendFormat": "{{ project }}:{{ ref }}:{{job_name}}"
    }
   ]
  },
  {
   "title": "SUCCESSFULLY COMPLETED",
   "type": "table-old",
   "gridPos": { "h": 26, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "max(time() - gitlab_ci_pipeline_job_timestamp{project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref, job_name, kind) unless max(gitlab_ci_pipeline_job_status{status!~\"success\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref, job_name, kind) > 0"
    },
    {
     "expr": "max(gitlab_ci_pipeline_job_duration_seconds{project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref, job_name, kind) unless (max(gitlab_ci_pipeline_job_status{status!~\"success\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref, job_name, kind) > 0)"
    },
    {
     "expr": "max(gitlab_ci_pipeline_job_status{project=~\"$OWNER.*\", ref=~\"$REF\", status=~\"success\"}) by (project, ref, job_name, kind, status) > 0"
    }
   ]
  },
  {
   "title": "RUNNING, FAILED OR NOT COMPLETED",
   "type": "table-old",
   "gridPos": { "h": 22, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max(time() - gitlab_ci_pipeline_job_timestamp{project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref, job_name, kind) unless (max(gitlab_ci_pipeline_job_status{status=~\"success\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref, job_name, kind) > 0)"
    },
    {
     "expr": "(max(gitlab_ci_pipeline_job_duration_seconds{project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref, job_name, kind) unless (max(gitlab_ci_pipeline_job_status{status=~\"success\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref, job_name, kind)) > 0)"
    },
    {
     "expr": "min(gitlab_ci_pipeline_job_status{status!~\"success\", project=~\"$OWNER.*\", ref=~\"$REF\"}) by (project, ref, job_name, kind, status) > 0"
    }
   ]
  }
 ]
}