{
 "title": "GitLab CI environments & deployments",
 "description": "This dashboard leverages the Prometheus exporter I wrote to fetch information about GitLab CI pipelines statuses. More information here: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "OWNER",
    "label": "owner",
    "query": "label_values(gitlab_ci_pipeline_id, project)"
   },
   {
    "name": "PROJECT",
    "label": "project",
    "query": "label_values(gitlab_ci_pipeline_id{project=~\"$OWNER.*\"}, project)"
   },
   {
    "name": "ENVIRONMENT",
    "label": "environment",
    "query": "label_values(gitlab_ci_pipeline_environment_information{project=~\"$OWNER.*\"}, environment)"
   }
  ]
 },
 "panels": [
  {
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gitlab_ci_pipeline_environment_behind_commits_count{project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT.*\"}",
     "legendFormat": "{{ project }} - {{ environment }}"
    }
   ]
  },
  {
   "title": "AVAILABLE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_environment_information{available=\"true\", project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "NOT UP TO DATE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_environment_behind_commits_count{project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT.*\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "title": "FAILED DEPLOYMENTS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_environment_status{status=\"failed\", project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT.*\"} > 0) or vector(0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": {
    "content": "<p style=\"text-align:center;\"><img src=\"https://www.cloudfoundry.org/wp-content/uploads/2017/10/icon_gitlab_cf@2x.png\" width=80px/></p>"
   }
  },
  {
   "title": "UNAVAILABLE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gitlab_ci_pipeline_environment_information{available=\"false\", project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Average environment deployment lag commits count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gitlab_ci_pipeline_environment_behind_commits_count{project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT\"})"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gitlab_ci_pipeline_environment_deployment_count[1m]) / increase(gitlab_ci_pipeline_environment_deployment_count[1m])",
     "legendFormat": "{{ environment }}:{{ project }}"
    }
   ]
  },
  {
   "title": "DEPLOYMENTS #",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(gitlab_ci_pipeline_environment_deployment_count{project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT.*\"}[1h]))"
    }
   ]
  },
  {
   "title": "Average environment deployment lag duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gitlab_ci_pipeline_environment_behind_duration_seconds{project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT\"})"
    }
   ]
  },
  {
   "title": "ENVIRONMENTS",
   "type": "table-old",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(time() - gitlab_ci_pipeline_environment_deployment_timestamp{project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT.*\"}) by (project, environment)"
    },
    {
     "expr": "max(gitlab_ci_pipeline_environment_deployment_duration_seconds{project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT.*\"}) by (project, environment)"
    },
    {
     "expr": "max(gitlab_ci_pipeline_environment_deployment_status{project=~\"$OWNER.*\", environment=~\"$ENVIRONMENT.*\"}) by (project, environment, status) > 0"
    },
    {
     "expr": "max(gitlab_ci_pipeline_environment_information) by (project, environment, author_email, current_commit_short_id, ref, latest_commit_short_id)"
    },
    {
     "expr": "max(gitlab_ci_pipeline_environment_behind_commits_count) by (project, environment)"
    },
    {
     "expr": "max(gitlab_ci_pipeline_environment_behind_duration_seconds) by (project, environment)"
    }
   ]
  }
 ]
}