---
kind: Kustomization
namespace: argocd

resources:
  - namespace.yml
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.1.5
  - ingress.yml
  - service-monitors.yml

patchesStrategicMerge:
  - patch-argocd-cm.yml
  - patch-argocd-rbac-cm.yml
  - patch-argocd-application-controller.yml
