---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  admin.enabled: "false"
  url: https://argocd.k3s.lama-corp.space
  dex.config: |
    connectors:
      - id: ldap
        type: ldap
        name: LDAP
        config:
          host: ldap.lama-corp.space:636
          insecureNoSSL: false
          insecureSkipVerify: false
          userSearch:
            baseDN: ou=users,dc=lama-corp,dc=space
            username: uid
            idAttr: DN
            emailAttr: mail
            nameAttr: givenName
          groupSearch:
            baseDN: ou=groups,dc=lama-corp,dc=space
            userAttr: DN
            groupAttr: member
            nameAttr: cn
      - id: oidc
        type: oidc
        name: Lama Corp. OIDC
        config:
          issuer: https://intra.lama-corp.space
          clientID: $oidc.lama-corp.clientID
          clientSecret: $oidc.lama-corp.clientSecret
          scopes:
            - profile
            - openid
            - email
            - roles
          promptType: none
          claimMapping:
            groups: roles
  resource.customizations: |
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jsonPointers:
        - /status
