---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: matrix-synapse-secret-files
spec:
  path: fsn-k3s/matrix/synapse-secret-files
  keys:
    - database.yaml
    - form_secret.yaml
    - macaroon_secret_key.yaml
    #- oidc_providers.yaml
    - registration_shared_secret.yaml
    - signing.key
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: matrix-appservice-slack
spec:
  path: fsn-k3s/matrix/appservice-slack
  keys:
    - slack.yaml
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: matrix-appservice-facebook
spec:
  path: fsn-k3s/matrix/appservice-facebook
  keys:
    - facebook.yaml
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: matrix-facebook-bridge-secret-files
spec:
  path: fsn-k3s/matrix/facebook-bridge-secret-files
  keys:
    - database.yml
    - public-shared-secret.yml
    - as-hs-tokens.yml
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: matrix-slack-bridge-secret-files
spec:
  path: fsn-k3s/matrix/slack-bridge-secret-files
  keys:
    - database.yml
    - oauth2.yml
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: matrix-maubot-secret-files
spec:
  path: fsn-k3s/matrix/maubot-secret-files
  keys:
    - database.yml
    - admins.yml
    - registration-shared-secret.yml
    - unshared-secret.yml
  type: Opaque
