---
apiVersion: v1
kind: Secret
metadata:
  name: gatus-prologin.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/gatus-prologin.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: slack-webhook
spec:
  path: fsn-k3s/gatus/prologin/discord-webhook
  keys:
    - DISCORD_WEBHOOK_URL
  type: Opaque
