# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/profiles/qemu-guest.nix>
    ];

  boot.initrd.luks.devices = [
    {
      name = "crypt-system-root";
      device = "/dev/disk/by-uuid/e3f5beef-60d4-4c51-9f66-bf3a366f7da7";
    }
    {
      name = "crypt-system-data";
      device = "/dev/disk/by-uuid/70c26d5e-667f-4f42-8866-b88b65c8e4c3";
    }
    {
       name = "crypt-swap";
       device = "/dev/disk/by-uuid/2c834f6a-64e3-405f-962d-9d860b3dfd66";
    }
  ];

  #TODO(low): refractor this, or not?

  # On crypt-system-root
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7f6c17eb-bf83-4766-af93-599c0eb37315";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  # On crypt-system-data
  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/fe50880d-cd8a-4d68-86bf-423c53e2f515";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  # On crypt-system-data
  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/fe50880d-cd8a-4d68-86bf-423c53e2f515";
      fsType = "btrfs";
      options = [ "subvol=@var" ];
    };

  # On crypt-system-data
  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/fe50880d-cd8a-4d68-86bf-423c53e2f515";
      fsType = "btrfs";
      options = [ "subvol=@opt" ];
    };

  # On crypt-system-data
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fe50880d-cd8a-4d68-86bf-423c53e2f515";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  # On crypt-system-data
  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/fe50880d-cd8a-4d68-86bf-423c53e2f515";
      fsType = "btrfs";
      options = [ "subvol=@homeroot" ];
    };

  # On crypt-system-data
  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/fe50880d-cd8a-4d68-86bf-423c53e2f515";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  # Management mounts

  # On crypt-system-root
  fileSystems."/mnt/system-root" =
    {
      device = "/dev/disk/by-uuid/7f6c17eb-bf83-4766-af93-599c0eb37315";        
      fsType = "btrfs";                                                         
    };                                                                          

  # On crypt-system-data
  fileSystems."/mnt/system-data" =
    {
      device = "/dev/disk/by-uuid/fe50880d-cd8a-4d68-86bf-423c53e2f515";        
      fsType = "btrfs";                                                         
    };                                                                          

  swapDevices = [
    # On crypt-swap
    { device = "/dev/disk/by-uuid/7ff1f98f-0cb2-41d4-85de-feea6fa9a4ad"; }
  ];

  # Snapshots configuration
  services.snapper = {
    snapshotInterval = "hourly";
    cleanupInterval = "daily";
    configs = {
      root = {
        fstype = "btrfs";
        subvolume = "/mnt/system-root/@root";
        extraConfig = ''
          SPACE_LIMIT=0.5
          FREE_LIMIT=0.2
          TIMELINE_CREATE=yes
          TIMELINE_CLEANUP=yes
          TIMELINE_LIMIT_HOURLY=24
          TIMELINE_LIMIT_DAILY=7
          TIMELINE_LIMIT_WEEKLY=5
          TIMELINE_LIMIT_MONTHLY=6
          TIMELINE_LIMIT_YEARLY=10
        '';
      };
      nix = {
        fstype = "btrfs";
        subvolume = "/mnt/system-data/@nix";
        extraConfig = ''
          SPACE_LIMIT=0.5
          FREE_LIMIT=0.2
          TIMELINE_CREATE=yes
          TIMELINE_CLEANUP=yes
          TIMELINE_LIMIT_HOURLY=24
          TIMELINE_LIMIT_DAILY=7
          TIMELINE_LIMIT_WEEKLY=5
          TIMELINE_LIMIT_MONTHLY=6
          TIMELINE_LIMIT_YEARLY=10
        '';
      };
      var = {
        fstype = "btrfs";
        subvolume = "/mnt/system-data/@var";
        extraConfig = ''
          SPACE_LIMIT=0.5
          FREE_LIMIT=0.2
          TIMELINE_CREATE=yes
          TIMELINE_CLEANUP=yes
          TIMELINE_LIMIT_HOURLY=24
          TIMELINE_LIMIT_DAILY=7
          TIMELINE_LIMIT_WEEKLY=5
          TIMELINE_LIMIT_MONTHLY=6
          TIMELINE_LIMIT_YEARLY=10
        '';
      };
      opt = {
        fstype = "btrfs";
        subvolume = "/mnt/system-data/@opt";
        extraConfig = ''
          SPACE_LIMIT=0.5
          FREE_LIMIT=0.2
          TIMELINE_CREATE=yes
          TIMELINE_CLEANUP=yes
          TIMELINE_LIMIT_HOURLY=24
          TIMELINE_LIMIT_DAILY=7
          TIMELINE_LIMIT_WEEKLY=5
          TIMELINE_LIMIT_MONTHLY=6
          TIMELINE_LIMIT_YEARLY=10
        '';
      };
      home = {
        fstype = "btrfs";
        subvolume = "/mnt/system-data/@home";
        extraConfig = ''
          SPACE_LIMIT=0.5
          FREE_LIMIT=0.2
          TIMELINE_CREATE=yes
          TIMELINE_CLEANUP=yes
          TIMELINE_LIMIT_HOURLY=24
          TIMELINE_LIMIT_DAILY=7
          TIMELINE_LIMIT_WEEKLY=5
          TIMELINE_LIMIT_MONTHLY=6
          TIMELINE_LIMIT_YEARLY=10
        '';
      };
      homeroot = {
        fstype = "btrfs";
        subvolume = "/mnt/system-data/@homeroot";
        extraConfig = ''
          SPACE_LIMIT=0.5
          FREE_LIMIT=0.2
          TIMELINE_CREATE=yes
          TIMELINE_CLEANUP=yes
          TIMELINE_LIMIT_HOURLY=24
          TIMELINE_LIMIT_DAILY=7
          TIMELINE_LIMIT_WEEKLY=5
          TIMELINE_LIMIT_MONTHLY=6
          TIMELINE_LIMIT_YEARLY=10
        '';
      };
      srv = {
        fstype = "btrfs";
        subvolume = "/mnt/system-data/@srv";
        extraConfig = ''
          SPACE_LIMIT=0.5
          FREE_LIMIT=0.2
          TIMELINE_CREATE=yes
          TIMELINE_CLEANUP=yes
          TIMELINE_LIMIT_HOURLY=24
          TIMELINE_LIMIT_DAILY=7
          TIMELINE_LIMIT_WEEKLY=5
          TIMELINE_LIMIT_MONTHLY=6
          TIMELINE_LIMIT_YEARLY=10
        '';
      };
    };
  };
}
