---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/gitlab.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: s3cmd-config
spec:
  path: fsn-k3s/gitlab/s3cmd-config
  keys:
    - config
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: objectstore
spec:
  path: fsn-k3s/gitlab/objectstore
  keys:
    - connection
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: registry-storage
spec:
  path: fsn-k3s/gitlab/registry-storage
  keys:
    - config
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: oidc-lama-corp
spec:
  path: fsn-k3s/gitlab/oidc-lama-corp
  keys:
    - provider
  type: Opaque
