---
kind: Kustomization
namespace: thefractalspace

commonLabels:
  app: thefractalspace

resources:
  - namespace.yml
  - pvc.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - secrets.yml
  - bot.yml

images:
  - name: thefractal.space
    newName: registry.gitlab.com/risson/thefractal.space/dockerize
    newTag: 978d33cf52f0dd706c65da35608012861a0e6867
  - name: brocoli
    newName: registry.gitlab.com/ddorn/brocoli
    newTag: 2c7d685795d7ac5836870194b7c8994f5d88ff48
