---
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/bitwarden.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: bitwarden-admin
spec:
  path: fsn-k3s/bitwarden/admin
  keys:
    - token
  type: Opaque
