---
kind: Kustomization
namespace: gatus

commonLabels:
  org: devoups

namePrefix: "devoups-"

resources:
  - ../../base
  - ingress.yml
  - secrets.yml

configMapGenerator:
  - name: gatus-configmap
    files:
      - config/config.yaml

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gatus
  spec:
    template:
      spec:
        containers:
          - name: gatus
            env:
              - name: SLACK_WEBHOOK_URL
                valueFrom:
                  secretKeyRef:
                    name: devoups-slack-webhook
                    key: SLACK_WEBHOOK_URL
              - name: FREE_MOBILE_SENDMSG_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: devoups-free-mobile-sendmsg-api-key
                    key: FREE_MOBILE_SENDMSG_API_KEY
              - name: FREE_MOBILE_SENDMSG_USER
                valueFrom:
                  secretKeyRef:
                    name: devoups-free-mobile-sendmsg-api-key
                    key: FREE_MOBILE_SENDMSG_USER
              - name: DB_HOST
                value: acid-main-cluster.postgres.svc.cluster.local
              - name: DB_PORT
                value: "5432"
              - name: DB_NAME
                value: gatus_devoups
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: gatus-devoups.acid-main-cluster.credentials
                    key: username
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: gatus-devoups.acid-main-cluster.credentials
                    key: password
