---
apiVersion: v1
kind: Secret
metadata:
  name: gatus-devoups.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/gatus-devoups.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: slack-webhook
spec:
  path: fsn-k3s/gatus/devoups/slack-webhook
  keys:
    - SLACK_WEBHOOK_URL
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: free-mobile-sendmsg-api-key
spec:
  path: fsn-k3s/gatus/devoups/free-mobile-sendmsg-api-key
  keys:
    - FREE_MOBILE_SENDMSG_USER
    - FREE_MOBILE_SENDMSG_API_KEY
  type: Opaque
