---
apiVersion: v1
kind: Secret
metadata:
  name: gatus-devoups.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/gatus-devoups.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: slack-webhook
spec:
  path: fsn-k3s/gatus/devoups/slack-webhook
  keys:
    - SLACK_WEBHOOK_URL
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: phowork-sms-gateway
spec:
  path: fsn-k3s/gatus/phowork/phowork-sms-gateway
  keys:
    - PHOWORK_SMS_GATEWAY_KEY
  type: Opaque
