---
kind: Kustomization
namespace: argocd

resources:
  - cert-manager.yml
  - ingress-nginx.yml
  - kubernetes-reflector.yml
  - lama-corp.space.yml
  - nfs-provisioner.yml
  - vault-secrets-operator.yml
