---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: vault-secrets-operator
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: vault-secrets-operator
  project: default
  source:
    chart: vault-secrets-operator
    repoURL: https://ricoberger.github.io/helm-charts
    targetRevision: 1.19.1
    helm:
      values: |
        vault:
          authMethod: kubernetes
          kubernetesPath: auth/fsn-k3s
          reconciliationTime: 60
          address: https://vault.lama-corp.space
        serviceMonitor:
          enabled: true
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: vaultsecrets.ricoberger.de
      jsonPointers:
        - /metadata/labels
