---
apiVersion: v1
kind: Secret
metadata:
  name: paperless.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/paperless.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: paperless-secret-key
spec:
  path: fsn-k3s/paperless/secret-key
  type: Opaque
