namespace: wikijs

commonLabels:
  org: lewdax

namePrefix: "lewdax-"

bases:
  - ../../base

resources:
  - secrets.yml
  - ingress.yml

patchesJson6902:
  - path: patch-deployment.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: wikijs

configMapGenerator:
  - name: wikijs-config
    behavior: merge
    literals:
      - DB_NAME=lewdax_wikijs
