---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-monitoring-crd
  labels:
    app: monitoring
    component: rancher-monitoring
spec:
  project: default
  syncPolicy:
    syncOptions:
      - Replace=true
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: cattle-monitoring-system
  source:
    repoURL: https://charts.rancher.io
    chart: rancher-monitoring-crd
    targetRevision: 100.1.0+up19.0.3
    helm: {}
