---
apiVersion: v1
kind: Secret
metadata:
  name: netbox.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/netbox.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: netbox-django-secrets
spec:
  path: fsn-k3s/netbox/django-secrets
  keys:
    - DJANGO_SECRET_KEY
  type: Opaque
