---
apiVersion: v1
kind: Secret
metadata:
  name: intranet.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/intranet.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ldap-admin-password
  namespace: intranet
spec:
  keys:
    - LDAP_ADMIN_PASSWORD
  type: Opaque
  path: fsn-k3s/intranet/ldap-admin-password
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: kerberos-admin-password
  namespace: intranet
spec:
  keys:
    - KRB5_ADMIN_PASSWORD
  type: Opaque
  path: fsn-k3s/intranet/kerberos-admin-password
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ldap-config-password
  namespace: intranet
spec:
  keys:
    - LDAP_CONFIG_PASSWORD
  type: Opaque
  path: fsn-k3s/intranet/ldap-config-password
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: ldap-keytab
spec:
  keys:
    - keytab
  isBinary: true
  type: Opaque
  path: fsn-k3s/intranet/ldap-keytab
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: spnego-keytab
  namespace: intranet
spec:
  keys:
    - keytab
  isBinary: true
  type: Opaque
  path: fsn-k3s/intranet/spnego-keytab
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: intranet-keytab
spec:
  keys:
    - keytab
  isBinary: true
  type: Opaque
  path: fsn-k3s/intranet/intranet-keytab
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: intranet-s3
spec:
  keys:
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
  type: Opaque
  path: fsn-k3s/intranet/s3
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: intranet-algolia
spec:
  keys:
    - DJANGO_ALGOLIA_APP_ID
    - DJANGO_ALGOLIA_API_KEY
    - DJANGO_ALGOLIA_SEARCH_API_KEY
  type: Opaque
  path: fsn-k3s/intranet/algolia
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: intranet-django-secrets
spec:
  keys:
    - DJANGO_DEFAULT_ADMIN_PASSWORD
    - DJANGO_SECRET_KEY
  type: Opaque
  path: fsn-k3s/intranet/django-secrets
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: kerberos-adm-secret
spec:
  keys:
    - adm-service-password
  type: Opaque
  path: fsn-k3s/intranet/kerberos
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: kerberos-kdc-secret
spec:
  keys:
    - adm-service-password
    - kdc-service-password
  type: Opaque
  path: fsn-k3s/intranet/kerberos
