{
 "title": "CPUs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"netdata.system.cpu.system\" WITH KEY = \"host\"\t"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "SHOW MEASUREMENTS WITH MEASUREMENT =~ /netdata.cpu*/"
   }
  ]
 },
 "panels": [
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Core utilization - $host",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "repeat": "host",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.cpu.cpu${cpu}\\..*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interrupts - $host",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "repeat": "host",
     "yaxes": [
      { "format": "short", "label": "interrupts/s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/netdata.cpu.cpu${cpu}_interrupts\\..*/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Interrupts - $host",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "interrupts/s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/netdata.cpu.cpu${cpu}_interrupts\\..*/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Softirqs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Softirqs - $host",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "repeat": "host",
     "yaxes": [
      { "format": "short", "label": "softirqs/s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/netdata.cpu.cpu${cpu}_softirqs\\..*/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Softnet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Softnet - $host",
     "type": "graph",
     "description": "Statistics for per CPUs core SoftIRQs related to network receive work. Total for all CPU cores can be found at System / softnet statistics. processed states the number of packets processed, dropped is the number packets dropped because the network device backlog was full (to fix them on Linux use sysctl to increase net.core.netdev_max_backlog), squeezed is the number of packets dropped because the network device budget ran out (to fix them on Linux use sysctl to increase net.core.netdev_budget and/or net.core.netdev_budget_usecs).",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "repeat": "host",
     "yaxes": [
      { "format": "short", "label": "events/s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/netdata.cpu.cpu${cpu}_softnet_stat\\..*/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Thermal Throttling Events - $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "repeat": "host",
     "yaxes": [
      { "format": "short", "label": "events/s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/netdata.cpu.core_throttling.cpu${cpu}/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cpufreq",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Frequency - $host",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "repeat": "host",
     "yaxes": [
      { "format": "short", "label": "MHz" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/netdata.cpu.cpufreq.cpu${cpu}/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}