{
 "title": "Unbound",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"netdata.system.cpu.system\" WITH KEY = \"host\"\t"
   }
  ]
 },
 "panels": [
  { "title": "Queries - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Received Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "alias": "queries",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.queries.queries",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Rate Limited Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "alias": "ratelimited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.queries_ip_ratelimited.ratelimited",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries By Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.queries_by_type.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries By Class",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.queries_by_class.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries By OpCode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.queries_by_opcode.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries By Flag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.queries_by_flag.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Queries - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Received Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "alias": "queries",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.queries.queries",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Rate Limited Queries",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "alias": "ratelimited",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.queries_ip_ratelimited.ratelimited",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries By Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.queries_by_type.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries By Class",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.queries_by_class.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries By OpCode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.queries_by_opcode.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Queries By Flag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "queries" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.queries_by_flag.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Replies - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }, "repeat": "host" },
  {
   "title": "Replies That Needed Recursive Processing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "replies" }
   ],
   "targets": [
    {
     "alias": "recursive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.recursive_replies.recursive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Replies By RCode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short", "label": "replies" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.replies_by_rcode.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Replies - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Replies That Needed Recursive Processing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "replies" }
   ],
   "targets": [
    {
     "alias": "recursive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.recursive_replies.recursive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Replies By RCode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short", "label": "replies" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/netdata.unbound_local.replies_by_rcode.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Recursion timings - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Time Spent On Recursive Processing",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.recursion_time.avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "median",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.recursion_time.median",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Recursion timings - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Spent On Recursive Processing",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.recursion_time.avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "median",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.recursion_time.median",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Cache - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 }, "repeat": "host" },
  {
   "title": "Cache Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short", "label": "events" }
   ],
   "targets": [
    {
     "alias": "hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache.hits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "miss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache.miss",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Statistics Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_percentage.hits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "miss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_percentage.miss",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Prefetches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short", "label": "prefetches" }
   ],
   "targets": [
    {
     "alias": "prefetches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_prefetch.prefetches",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Replies Served From Expired Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short", "label": "replies" }
   ],
   "targets": [
    {
     "alias": "zero ttl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.zero_ttl_replies.zero_ttl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Items Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short", "label": "items" }
   ],
   "targets": [
    {
     "alias": "infra",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_count.infra",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_count.key",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "msg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_count.msg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "rrset",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_count.rrset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Cache - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Cache Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short", "label": "events" }
   ],
   "targets": [
    {
     "alias": "hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache.hits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "miss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache.miss",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Statistics Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_percentage.hits",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "miss",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_percentage.miss",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Prefetches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short", "label": "prefetches" }
   ],
   "targets": [
    {
     "alias": "prefetches",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_prefetch.prefetches",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Replies Served From Expired Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "yaxes": [
    { "format": "short", "label": "replies" }
   ],
   "targets": [
    {
     "alias": "zero ttl",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.zero_ttl_replies.zero_ttl",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Items Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short", "label": "items" }
   ],
   "targets": [
    {
     "alias": "infra",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_count.infra",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "key",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_count.key",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "msg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_count.msg",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "rrset",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "netdata.unbound_local.cache_count.rrset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Request list - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Request List Usage",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "queries" }
     ],
     "targets": [
      {
       "alias": "avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.request_list_usage.avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.request_list_usage.max",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Current Request List Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "queries" }
     ],
     "targets": [
      {
       "alias": "all",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.current_request_list_usage.all",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "user",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.current_request_list_usage.user",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Request List Jostle List Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "queries" }
     ],
     "targets": [
      {
       "alias": "dropped",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.request_list_jostle_list.dropped",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "overwritten",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.request_list_jostle_list.overwritten",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Request list - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request List Usage",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "queries" }
     ],
     "targets": [
      {
       "alias": "avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.request_list_usage.avg",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.request_list_usage.max",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Current Request List Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "queries" }
     ],
     "targets": [
      {
       "alias": "all",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.current_request_list_usage.all",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "user",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.current_request_list_usage.user",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Request List Jostle List Events",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short", "label": "queries" }
     ],
     "targets": [
      {
       "alias": "dropped",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.request_list_jostle_list.dropped",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "overwritten",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.request_list_jostle_list.overwritten",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "TCP buffers - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Handler Buffers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "buffers" }
     ],
     "targets": [
      {
       "alias": "usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.tcpusage.usage",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "TCP buffers - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 139 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Handler Buffers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "buffers" }
     ],
     "targets": [
      {
       "alias": "usage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.tcpusage.usage",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "message",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.cache_memory.message",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "rrset",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.cache_memory.rrset",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Module Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "iterator",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.mod_memory.iterator",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "respip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.mod_memory.respip",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "validator",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.mod_memory.validator",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP and TLS Stream Waif Buffer Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "streamwait",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.mem_stream_wait.streamwait",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "message",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.cache_memory.message",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "rrset",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.cache_memory.rrset",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Module Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "iterator",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.mod_memory.iterator",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "respip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.mod_memory.respip",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "validator",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.mod_memory.validator",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "TCP and TLS Stream Waif Buffer Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "streamwait",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.mem_stream_wait.streamwait",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Update - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "uptime",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.uptime.time",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Update - $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "uptime",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netdata.unbound_local.uptime.time",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}