---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cloudflare-lama-corp-api-token-secret
spec:
  path: fsn-k3s/cert-manager/cloudflare-lama-corp-api-token
  keys:
    - api-token
  type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns-issuer-lama-corp.space
spec:
  acme:
    email: caa@lama-corp.space
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: dns-issuer-lama-corp-account-key
    solvers:
      - dns01:
          cloudflare:
            email: marc.schmitt@lama-corp.space
            apiTokenSecretRef:
              name: cloudflare-lama-corp-api-token-secret
              key: api-token
