---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
data:
  db_hosted_zone: postgres.k3s.lama-corp.space
  workers: "1"

  enable_crd_validation: "true"
  enable_lazy_spilo_upgrade: "false"
  enable_shm_volume: "true"

  delete_annotation_date_key: "delete-date"
  delete_annotation_name_key: "delete-clustername"

  inherited_annotations: reflector.v1.k8s.emberstack.com/reflection-allowed,reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces

  logical_backup_docker_image: registry.gitlab.com/lama-corp/infra/tools/postgres-logical-backup/master:deae65379445cd28d6dd5ec9c41b96897ef04674
  logical_backup_s3_bucket: postgres.k3s.lama-corp.space
  logical_backup_s3_endpoint: http://minio.minio.svc.cluster.local:9000
  logical_backup_s3_sse: ""
  logical_backup_s3_access_key_id: "/etc/postgres-secrets/AWS_ACCESS_KEY_ID"
  logical_backup_s3_secret_access_key: "/etc/postgres-secrets/AWS_SECRET_ACCESS_KEY"

  additional_secret_mount: postgres-pod-secrets
  additional_secret_mount_path: /etc/postgres-secrets/
