---
kind: Kustomization
namespace: nextcloud

commonLabels:
  app: nextcloud

resources:
  - namespace.yml
  - pvc.yml
  - secrets.yml
  - deployment.yml
  - cronjob.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: nextcloud-config
    literals:
      - NEXTCLOUD_DATA_DIR=/data
      - NEXTCLOUD_UPDATE=0

      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.lama-corp.space
      - SMTP_HOST=mail-1.vrt.fsn.lama-corp.space
      - SMTP_PORT=25
      - SMTP_AUTHTYPE=PLAIN
      - MAIL_FROM_ADDRESS=nextcloud
      - MAIL_DOMAIN=lama-corp.space

images:
  - name: nextcloud
    newTag: 23.0.1-apache
