---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/nextcloud.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: nextcloud-admin-user
spec:
  path: fsn-k3s/nextcloud/admin-user
  keys:
    - username
    - password
  type: Opaque
