{
  imports = [
    ./general/editor.nix
    ./general/home-manager.nix
    ./general/keyboard.nix
    ./general/security.nix
    ./general/users.nix
    ./hardware/fwupd.nix
    ./hardware/intel_backlight.nix
    ./hardware/serial_console.nix
    ./services/docker.nix
    ./services/libvirt.nix
    ./services/printers.nix
    ./services/ssh.nix
    ./software/curl.nix
    ./software/general.nix
    ./software/neovim.nix
    ./software/tmux.nix
    ./software/zsh.nix
    ./workstation/autorandr.nix
    ./workstation/bluetooth.nix
    ./workstation/fonts.nix
    ./workstation/gtk.nix
    ./workstation/power.nix
    ./workstation/sound.nix
    ./workstation/xorg.nix
    ./workstation/yubikey.nix
  ];
}
