{
 "title": "Gatus Overview",
 "tags": [ "gatus" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "All tasks executed over time",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_tasks[30s])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Unsuccessful tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_tasks{success=\"false\"}[30s])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Successful tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gatus_tasks{success=\"true\"}[30s])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}