{
  imports = [
    ./generic/keyboard.nix
    ./generic/nixos.nix
    ./services/gnupg.nix
    ./services/lowbatt.nix
    ./services/weechat.nix
    ./software/fzf.nix
    ./software/git.nix
    ./software/htop.nix
    ./software/keybase.nix
    ./software/less.nix
    ./software/neovim.nix
    ./software/packages.nix
    ./software/ssh.nix
    ./software/taskwarrior.nix
    ./software/tmux.nix
    ./software/zsh
    ./theme
    ./theme/gruvbox
    ./theme/seoul256-dark
    ./workstation/autorandr.nix
    ./workstation/bluetooth.nix
    ./workstation
    ./workstation/dunst.nix
    ./workstation/email.nix
    ./workstation/firefox.nix
    ./workstation/gtk.nix
    ./workstation/i3/bar
    ./workstation/i3
    ./workstation/locker.nix
    ./workstation/rofi
    ./workstation/urxvt.nix
    ./workstation/window-manager.nix
  ];
}
