---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-main-cluster
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
spec:
  teamId: "acid"
  volume:
    size: 50Gi
  numberOfInstances: 1

  # users: name -> permissions (usually [])
  users:
    bitwarden: []
    catcdc: []
    intranet: []
    gatus_devoups: []
    gatus_phowork: []
    gitlab: []
    hedgedoc: []
    lewdax_wikijs: []
    mattermost: []
    matrix: []
    matrix_facebook_bridge: []
    matrix_maubot: []
    matrix_slack_bridge: []
    netbox: []
    nextcloud: []
    paperless: []
    scoreboard_seedbox_cri: []

  # databases: name -> owner
  databases:
    bitwarden: bitwarden
    catcdc: catcdc
    intranet: intranet
    gatus_devoups: gatus_devoups
    gatus_phowork: gatus_phowork
    gitlabhq_production: gitlab
    hedgedoc: hedgedoc
    lewdax_wikijs: lewdax_wikijs
    mattermost: mattermost
    matrix: matrix
    matrix_facebook_bridge: matrix_facebook_bridge
    matrix_maubot: matrix_maubot
    matrix_slack_bridge: matrix_slack_bridge
    netbox: netbox
    nextcloud: nextcloud
    paperless: paperless
    scoreboard_seedbox_cri: scoreboard_seedbox_cri

  postgresql:
    version: "13"

  resources:
    requests:
      cpu: "1"
      memory: "1G"
    limits:
      cpu: "4"
      memory: "8G"

  enableLogicalBackup: true
  logicalBackupSchedule: "17 5 * * *"

  sidecars:
    - name: "exporter"
      image: quay.io/prometheuscommunity/postgres-exporter:v0.11.0
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 256M
        requests:
          cpu: 100m
          memory: 200M
      env:
        - name: DATA_SOURCE_URI
          value: "acid-main-cluster?sslmode=require"
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: postgres.acid-main-cluster.credentials
              key: username
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres.acid-main-cluster.credentials
              key: password
        - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
          value: "true"
