---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: postgres-pod-secrets
spec:
  path: fsn-k3s/postgres/pod-secrets
  keys:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  type: Opaque
