---
apiVersion: v1
kind: Secret
metadata:
  name: catcdc.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/catcdc.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: catcdc-s3
spec:
  path: fsn-k3s/catcdc/s3
  keys:
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: catcdc-epita-oidc
spec:
  path: fsn-k3s/catcdc/epita-oidc
  keys:
    - SOCIAL_AUTH_EPITA_KEY
    - SOCIAL_AUTH_EPITA_SECRET
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: catcdc-django-secrets
spec:
  path: fsn-k3s/catcdc/django-secrets
  keys:
    - DJANGO_SECRET_KEY
  type: Opaque
