---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    org: lama-corp
    type: app
    app: netbox
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: netbox
  project: default
  source:
    repoURL: https://gitlab.com/lama-corp/infra/dotshabka.git
    path: k3s/apps/netbox
    targetRevision: HEAD
