---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scoreboard-seedbox-cri
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    org: lama-corp
    type: app
    app: scoreboard-seedbox-cri
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: scoreboard-seedbox-cri
  project: default
  source:
    repoURL: https://gitlab.com/lama-corp/infra/dotshabka.git
    path: k3s/apps/scoreboard-seedbox-cri
    targetRevision: HEAD
