metrics: true
maintenance:
  enabled: true
  start: "21:00"
  duration: "3h"
storage:
  type: postgres
  path: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require"
ui:
  title: devoups.
  logo: https://s3.cri.epita.fr/cri-intranet/img/logo.png
alerting:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}
    default-alert:
      enabled: true
      failure-threshold: 3
      success-threshold: 2
      send-on-resolved: true
  custom:
    url: https://sms.phowork.fr:5001/sms
    method: POST
    headers:
      Authorization: "Basic ${PHOWORK_SMS_GATEWAY_KEY}"
      Content-Type: application/json
    body: |
      {
        "dest_contact_name": "charles",
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [SERVICE_NAME] - [ALERT_DESCRIPTION]"
      }
    default-alert:
      enabled: true
      failure-threshold: 5
      success-threshold: 3
      send-on-resolved: false
endpoints:
  ###
  # Critical
  ###

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Intranet CRI
    group: critical
    url: https://cri.epita.fr/healthz
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: LDAP CRI
    group: critical
    url: "tls://ldap.pie.cri.epita.fr:636"
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    interval: 30s
    name: DNS
    group: critical
    url: tcp://ns.cri.epita.fr:53
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: GitLab
    group: critical
    url: https://gitlab.cri.epita.fr/-/health
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: GitLab registry
    group: critical
    url: https://registry.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Vault
    group: critical
    url: https://vault.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: S3
    group: critical
    url: https://s3.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    interval: 30s
    name: Console Bocal
    group: critical
    url: https://console.bocal.org
    alerts:
      - type: slack
      - type: custom

  ###
  # PIE SM
  ###

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Fleet manager
    group: PIE SM
    url: https://fleet.pie.cri.epita.fr/healthz
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Django PXE
    group: PIE SM
    url: https://django-pxe.pie.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: iPXE
    group: PIE SM
    url: https://ipxe.pie.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    interval: 30s
    name: Bttrack
    group: PIE SM
    url: tcp://torrent.pie.cri.epita.fr:8000
    alerts:
      - type: slack
      - type: custom

  ###
  # Student services
  ###

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Moodle (cours)
    group: Student services
    url: https://moodle.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Moodle (exams)
    group: Student services
    url: https://moodle-exam.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Moodle (recrutement)
    group: Student services
    url: https://recrutements.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Rocket.Chat
    group: Student services
    url: https://rocketchat.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    interval: 30s
    name: News
    group: Student services
    url: tcp://news.epita.fr:119
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    interval: 30s
    name: Git
    group: Student services
    url: tcp://git.cri.epita.fr:22
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Wiki prog
    group: Student services
    url: https://wiki-prog.infoprepa.epita.fr
    alerts:
      - type: slack
      - type: custom

  ###
  # Assistants services
  ###

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Intranet Assistants
    group: Assistants services
    url: https://intra.assistants.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    interval: 30s
    name: Git Assistants
    group: Assistants services
    url: tcp://git.assistants.epita.fr:22
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: k8s assistants-prod-1 ArgoCD
    url: https://argocd.prod-1.k8s.assistants.epita.fr
    group: Assistants services
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: k8s assistants-prod-1 Prometheus
    url: https://prometheus.prod-1.k8s.assistants.epita.fr
    group: Assistants services

  ###
  # Internal services
  ###

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: k8s ArgoCD
    group: Internal services
    url: https://argocd.undercloud.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: k8s prod-1 Prometheus
    group: Internal services
    url: https://prometheus.prod-1.k8s.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: k8s ops Prometheus
    group: Internal services
    url: https://prometheus.ops.k8s.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: k8s ops Grafana
    group: Internal services
    url: https://grafana.ops.k8s.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Bookstack
    group: Internal services
    url: https://bookstack.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Mail
    group: Internal services
    url: starttls://mail.cri.epita.fr:587
    alerts:
      - type: slack
      - type: custom

  ###
  # Kerberos
  ###

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    interval: 30s
    name: Kerberos KDC ticket server
    group: Authentication
    url: tcp://kerberos.pie.cri.epita.fr:88
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    interval: 30s
    name: LDAP
    group: Authentication
    url: tcp://ldap.pie.cri.epita.fr:389
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[CONNECTED] == true'
    - '[RESPONSE_TIME] <= 1000'
    interval: 30s
    name: LDAPS
    group: Authentication
    url: tcp://ldap.pie.cri.epita.fr:636
    alerts:
      - type: slack
      - type: custom

  ###
  # Others
  ###

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: MaaS
    group: others
    url: https://maas.cri.epita.fr/q/health
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 401'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: OIDC redirection
    group: others
    url: https://tickets.cri.epita.fr

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1500'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Blog
    group: others
    url: https://blog.cri.epita.fr
    alerts:
      - type: slack
      - type: custom

  - conditions:
    - '[STATUS] == 200'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: Documentation
    group: others
    url: https://doc.cri.epita.fr

  - conditions:
    - '[STATUS] == 401'
    - '[RESPONSE_TIME] <= 1000'
    - '[CERTIFICATE_EXPIRATION] > 168h' # 7 days
    interval: 30s
    name: HTTPS redirection
    group: others
    url: https://tickets.cri.epita.fr
