---
# We reuse Renovate token as it does not have any special permissions and it
# just makes our life easier. Feel free to swap that out.
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: gitlab-token
spec:
  path: fsn-k3s/gitlab-ci-pipeline-exporter/gitlab-token
  type: Opaque
