---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-ci-exporter
  labels:
    app: gitlab-ci-exporter
spec:
  selector:
    matchLabels:
      app: gitlab-ci-exporter
  endpoints:
    - port: http
      interval: 10s
