---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ci-exporter
  labels:
    app: gitlab-ci-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: gitlab-ci-exporter
