{
  imports = [
    ./common/backups.nix
    ./common/boot.nix
    ./common/common.nix
    ./common/kernel.nix
    ./common/keyboard.nix
    ./common/locale.nix
    ./common/neovim.nix
    ./common/nix.nix
    ./common/packages.nix
    ./common/users.nix
    ./ldap
    ./luks
    ./minio
    ./netdata
    ./postgresql
    ./sendmail
    ./ssh
    ./unbound
    ./zfs
  ];
}
