---
kind: Kustomization
namespace: scoreboard-seedbox-cri

commonLabels:
  app: scoreboard-seedbox-cri

resources:
  - namespace.yml
  - secrets.yml
  - init-job.yml
  - deployment.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: scoreboard-config
    literals:
      - DJANGO_LOG_LEVEL=info
      - DJANGO_DB_HOST=acid-main-cluster.postgres.svc.cluster.local
      - DJANGO_DB_NAME=scoreboard_seedbox_cri
      - S3_ENDPOINT=https://s3.lama-corp.space
      - S3_CUSTOM_DOMAIN=s3.lama-corp.space/scoreboard-seedbox-cri
      - S3_SECURE_URLS=1
      - S3_BUCKET=scoreboard-seedbox-cri
      - DJANGO_ALLOWED_HOSTS=scoreboard-seedbox-cri.risson.space
      - DJANGO_ADMINS=root@lama-corp.space
  - name: scoreboard-secret-path
    literals:
      - DJANGO_DB_USER_FILE=/etc/scoreboard-postgres-auth/username
      - DJANGO_DB_PASSWORD_FILE=/etc/scoreboard-postgres-auth/password

      - S3_ACCESS_KEY_FILE=/etc/scoreboard-s3/S3_ACCESS_KEY
      - S3_SECRET_KEY_FILE=/etc/scoreboard-s3/S3_SECRET_KEY

      - DJANGO_SOCIAL_AUTH_EPITA_KEY_FILE=/etc/scoreboard-epita-oidc/SOCIAL_AUTH_EPITA_KEY
      - DJANGO_SOCIAL_AUTH_EPITA_SECRET_FILE=/etc/scoreboard-epita-oidc/SOCIAL_AUTH_EPITA_SECRET

      - DJANGO_SECRET_KEY_FILE=/etc/scoreboard-django-secrets/DJANGO_SECRET_KEY

images:
  - name: registry.cri.epita.fr/risson/scoreboard-seedbox-cri/master
    newTag: fa745b6fb9ff13703483e8f37d0a1a8170e215dc
