---
apiVersion: v1
kind: Secret
metadata:
  name: scoreboard-seedbox-cri.acid-main-cluster.credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "postgres/scoreboard-seedbox-cri.acid-main-cluster.credentials"
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: scoreboard-s3
spec:
  path: fsn-k3s/scoreboard-seedbox-cri/s3
  keys:
    - S3_ACCESS_KEY
    - S3_SECRET_KEY
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: scoreboard-epita-oidc
spec:
  path: fsn-k3s/scoreboard-seedbox-cri/epita-oidc
  keys:
    - SOCIAL_AUTH_EPITA_KEY
    - SOCIAL_AUTH_EPITA_SECRET
  type: Opaque
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: scoreboard-django-secrets
spec:
  path: fsn-k3s/scoreboard-seedbox-cri/django-secrets
  keys:
    - DJANGO_SECRET_KEY
  type: Opaque
