---

version: 1

formatters:
  structued:
    class: synapse.logging.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: structued

loggers:
  synapse.storage.SQL:
    # beware: increasing this to DEBUG will make synapse log sensitive
    # information such as access tokens.
    level: INFO

  twisted:
    handlers: [console]
    propagate: false

  ldap3:
    handlers: [console]
    propagate: false

  ldap_auth_provider:
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]

disable_existing_loggers: false
