---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-k3s.fsn-readwriteonce
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "true"
